Repository ECE651-Group-15/mobile, pull requests merged in 2024-03, with the labels that each got.

#47 MB-8: fix the bug
  lib/common/routes/names.dart
  lib/common/store/user.dart
  lib/global.dart
  lib/pages/create_post/controller.dart
  lib/pages/home/view.dart
  lib/pages/my_post/controller.dart
Labels: bug

#52 Mb 24
  lib/pages/edit_profile/controller.dart
  lib/pages/edit_profile/state.dart
  lib/pages/edit_profile/view.dart
  lib/pages/my_profile_page/view.dart
Labels: task/user story

#67 finished delete user profile
  lib/common/apis/post.dart
  lib/common/entities/post.dart
  lib/pages/my_profile_page/controller.dart
  lib/pages/my_profile_page/view.dart
Labels: task/user story

#69 Mb 30
  integration_test/login_test.dart
  integration_test/logout_test.dart
  pubspec.lock
  pubspec.yaml
Labels: test

#72 Mb 33
  lib/common/apis/post.dart
  lib/common/entities/post.dart
  lib/common/style/color.dart
  lib/pages/home/controller.dart
  lib/pages/home/view.dart
  lib/pages/image_post/controller.dart
  lib/pages/image_post/state.dart
  lib/pages/image_post/view.dart
Labels: task/user story

#78 changed email registration for only uwaterloo.ca
  integration_test/logout_test.dart
  lib/pages/sign_up_pages/controller.dart
  pubspec.lock
Labels: task/user story

#79 finished create account test
  integration_test/create_account.dart
Labels: test

#81 MB-34: user can mark post as sold
  lib/common/apis/post.dart
  lib/common/entities/post.dart
  lib/common/routes/names.dart
  lib/common/routes/pages.dart
  lib/pages/completed_order_page/bindings.dart
  lib/pages/completed_order_page/controller.dart
  lib/pages/completed_order_page/index.dart
  lib/pages/completed_order_page/state.dart
  lib/pages/completed_order_page/view.dart
  lib/pages/mine/view.dart
  lib/pages/my_post/controller.dart
  lib/pages/my_post/view.dart
Labels: task/user story

#92 Mb 40
  integration_test/receive_chat.dart
  integration_test/test_chat.dart
  lib/pages/chat/view.dart
  lib/pages/home/view.dart
  lib/pages/message/view.dart
Labels: test

#94 Mb 41
  integration_test/change avatar_test.dart
  integration_test/check_unsold.dart
  integration_test/ct.dart
  integration_test/mark_sold_and_unsold.dart
  integration_test/search_test.dart
  integration_test/test_editpost.dart
  lib/pages/create_post/controller.dart
  lib/pages/edit_post/controller.dart
  lib/pages/home/view.dart
  pubspec.lock
  pubspec.yaml
  unit_test/completed_order_test.dart
Labels: test
